# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler libudunits2-dev libnode-dev libv8-dev