language: r
warnings_are_errors: true
cache: packages

matrix:
  include:
    - r: oldrel
    - os: linux
      dist: trusty
      r: release
      env: NOT_CRAN=true
    - os: osx
      r: release
      env: NOT_CRAN=true
      addons:
        homebrew:
          packages:
          - cairo
    - os: linux
      dist: xenial
      r: devel
      env: NOT_CRAN=false
      r_github_packages:
        - r-lib/covr
      before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
      after_success:
        - Rscript -e 'covr::codecov()'
addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
notifications:
  email:
    recipients:
      - s.vissault@yahoo.fr
      - kevin.cazelles@gmail.com
    on_success: always
    on_failure: always
        


