language: r
warnings_are_errors: true
sudo: required
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      env: NOT_CRAN=true
    - os: osx
      r: release
      env: NOT_CRAN=true
    - os: linux
      dist: trusty
      r: devel
      env: NOT_CRAN=false

notifications:
  slack:
    rooms: insileco:c6N7g4s36dNHpAxrI2QdattF
    on_success: always
    on_failure: always # change or never
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "See on Travis: %{build_url}"
      - "duration: %{duration}"
  email:
    on_success: never
    on_failure: never


before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo add-apt-repository ppa:ubuntugis/ppa --yes; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get --yes --force-yes update -qq; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev; fi
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'


r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
