# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
warnings_are_errors: false

language: r
cache: packages
sudo: required
dist: trusty

repos: 
  CRAN: https://cran.rstudio.com
  rforge: http://R-Forge.R-project.org

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler libv8-dev libjq-dev
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'